// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatUserFieldNames          = builder.RawFieldNames(&ChatUser{})
	chatUserRows                = strings.Join(chatUserFieldNames, ",")
	chatUserRowsExpectAutoSet   = strings.Join(stringx.Remove(chatUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatUserRowsWithPlaceHolder = strings.Join(stringx.Remove(chatUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChatUserIdPrefix           = "cache:chatUser:id:"
	cacheChatUserChatIdUserIdPrefix = "cache:chatUser:chatId:userId:"
)

type (
	chatUserModel interface {
		Insert(ctx context.Context, data *ChatUser) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ChatUser, error)
		FindOneByChatIdUserId(ctx context.Context, chatId uint64, userId uint64) (*ChatUser, error)
		Update(ctx context.Context, data *ChatUser) error
		Delete(ctx context.Context, id uint64) error
		FindPage(ctx context.Context, page, pageSize int64) ([]ChatUser, int64, error)
		FindChunk(ctx context.Context, limit int64, lastId uint64) ([]ChatUser, uint64, error)
	}

	defaultChatUserModel struct {
		sqlc.CachedConn
		table string
	}

	ChatUser struct {
		Id        uint64 `db:"id"`         // 主键 ID
		ChatId    uint64 `db:"chat_id"`    // 聊天 ID
		UserId    uint64 `db:"user_id"`    // 用户 ID
		JoinedAt  int64  `db:"joined_at"`  // 加入时间(秒级时间戳)
		CreatedAt int64  `db:"created_at"` // 创建时间(秒级时间戳)
		UpdatedAt int64  `db:"updated_at"` // 更新时间(秒级时间戳)
	}
)

func newChatUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultChatUserModel {
	return &defaultChatUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`chat_user`",
	}
}

func (m *defaultChatUserModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	chatUserChatIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheChatUserChatIdUserIdPrefix, data.ChatId, data.UserId)
	chatUserIdKey := fmt.Sprintf("%s%v", cacheChatUserIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 检查是否有 deleted_at 字段：通过检查结构体字段名列表
		fieldNames := builder.RawFieldNames(&ChatUser{})
		fieldNamesStr := strings.Join(fieldNames, ",")
		hasDeletedAt := strings.Contains(fieldNamesStr, "deleted_at")

		var query string
		if hasDeletedAt {
			// 软删除：设置 deleted_at 为当前时间戳
			query = fmt.Sprintf("update %s set deleted_at = UNIX_TIMESTAMP(), updated_at = UNIX_TIMESTAMP() where `id` = ? and deleted_at = 0", m.table)
		} else {
			// 物理删除：直接删除记录
			query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
		}
		return conn.ExecCtx(ctx, query, id)
	}, chatUserChatIdUserIdKey, chatUserIdKey)
	return err
}

func (m *defaultChatUserModel) FindOne(ctx context.Context, id uint64) (*ChatUser, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(chatUserRows, "deleted_at")
	whereClause := "where `id` = ?"
	if hasDeletedAt {
		whereClause += " and deleted_at = 0"
	}
	chatUserIdKey := fmt.Sprintf("%s%v", cacheChatUserIdPrefix, id)
	var resp ChatUser
	err := m.QueryRowCtx(ctx, &resp, chatUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s %s limit 1", chatUserRows, m.table, whereClause)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatUserModel) FindOneByChatIdUserId(ctx context.Context, chatId uint64, userId uint64) (*ChatUser, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(chatUserRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	chatUserChatIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheChatUserChatIdUserIdPrefix, chatId, userId)
	var resp ChatUser
	err := m.QueryRowIndexCtx(ctx, &resp, chatUserChatIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `chat_id` = ? and `user_id` = ?%s limit 1", chatUserRows, m.table, andClause)
		if err := conn.QueryRowCtx(ctx, &resp, query, chatId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatUserModel) Insert(ctx context.Context, data *ChatUser) (sql.Result, error) {
	// 自动设置创建时间和更新时间
	if data.CreatedAt == 0 {
		data.CreatedAt = time.Now().Unix()
	}
	if data.UpdatedAt == 0 {
		data.UpdatedAt = time.Now().Unix()
	}
	// 注意：如果表没有 deleted_at 字段，data.DeletedAt 将不存在，不能访问
	// deleted_at 字段如果存在，它已经在 RowsExpectAutoSet 中，不需要特殊处理
	chatUserChatIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheChatUserChatIdUserIdPrefix, data.ChatId, data.UserId)
	chatUserIdKey := fmt.Sprintf("%s%v", cacheChatUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 手动构建包含 created_at、updated_at 的插入语句
		// 如果表有 deleted_at 字段，它已经在 RowsExpectAutoSet 中，不需要重复添加
		query := fmt.Sprintf("insert into %s (%s, `created_at`, `updated_at`) values (?, ?, ?, ?, ?)", m.table, chatUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ChatId, data.UserId, data.JoinedAt, data.CreatedAt, data.UpdatedAt)
	}, chatUserChatIdUserIdKey, chatUserIdKey)
	return ret, err
}

func (m *defaultChatUserModel) Update(ctx context.Context, newData *ChatUser) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	chatUserChatIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheChatUserChatIdUserIdPrefix, data.ChatId, data.UserId)
	chatUserIdKey := fmt.Sprintf("%s%v", cacheChatUserIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 自动设置更新时间
		newData.UpdatedAt = time.Now().Unix()
		// 检查是否有 deleted_at 字段
		hasDeletedAt := strings.Contains(chatUserRowsWithPlaceHolder, "deleted_at")
		// 手动构建包含 updated_at 的更新语句
		whereClause := "where `id` = ?"
		if hasDeletedAt {
			whereClause += " and deleted_at = 0"
		}
		query := fmt.Sprintf("update %s set %s, `updated_at` = %d %s", m.table, chatUserRowsWithPlaceHolder, newData.UpdatedAt, whereClause)
		return conn.ExecCtx(ctx, query, newData.ChatId, newData.UserId, newData.JoinedAt, newData.Id)
	}, chatUserChatIdUserIdKey, chatUserIdKey)
	return err
}

func (m *defaultChatUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChatUserIdPrefix, primary)
}

func (m *defaultChatUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(chatUserRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	query := fmt.Sprintf("select %s from %s where `id` = ?%s limit 1", chatUserRows, m.table, andClause)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChatUserModel) tableName() string {
	return m.table
}

// 分页查询：根据页码和每页数量查询数据
func (m *defaultChatUserModel) FindPage(ctx context.Context, page, pageSize int64) ([]ChatUser, int64, error) {
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 20
	}
	if pageSize > 100 {
		pageSize = 100
	}

	offset := (page - 1) * pageSize

	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(chatUserRows, "deleted_at")
	whereClause := ""
	if hasDeletedAt {
		whereClause = "where deleted_at = 0"
	}

	// 查询总数
	var total int64
	countQuery := fmt.Sprintf("select count(*) from %s %s", m.table, whereClause)
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery)
	if err != nil {
		return nil, 0, err
	}

	// 查询分页数据
	var list []ChatUser
	query := fmt.Sprintf("select %s from %s %s order by id desc limit %d offset %d", chatUserRows, m.table, whereClause, pageSize, offset)
	err = m.QueryRowsNoCacheCtx(ctx, &list, query)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

// 分片查询：基于lastId的分片查询，一次查询limit条，返回数据和下次查询的lastId
// lastId=0表示第一次查询，返回的lastId用于下次查询，当返回的lastId=0或数据为空时表示无更多数据
func (m *defaultChatUserModel) FindChunk(ctx context.Context, limit int64, lastId uint64) ([]ChatUser, uint64, error) {
	if limit <= 0 {
		limit = 20
	}
	if limit > 100 {
		limit = 100
	}

	var list []ChatUser
	var err error

	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(chatUserRows, "deleted_at")
	whereClause := ""
	if hasDeletedAt {
		whereClause = "where deleted_at = 0"
	}

	if lastId == 0 {
		// 第一次查询
		query := fmt.Sprintf("select %s from %s %s order by id asc limit %d", chatUserRows, m.table, whereClause, limit)
		err = m.QueryRowsNoCacheCtx(ctx, &list, query)
	} else {
		// 基于lastId的分片查询
		andClause := ""
		if hasDeletedAt {
			andClause = "where deleted_at = 0 and id > ?"
		} else {
			andClause = "where id > ?"
		}
		query := fmt.Sprintf("select %s from %s %s order by id asc limit %d", chatUserRows, m.table, andClause, limit)
		err = m.QueryRowsNoCacheCtx(ctx, &list, query, lastId)
	}

	if err != nil {
		return nil, 0, err
	}

	// 返回最后一条记录的ID，用于下次查询；如果数据为空，返回0表示无更多数据
	nextLastId := uint64(0)
	if len(list) > 0 {
		nextLastId = list[len(list)-1].Id
	}

	return list, nextLastId, nil
}
