// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiCreateReq struct {
	Name        string `json:"name"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type ApiDeleteReq struct {
	Id uint64 `json:"id"`
}

type ApiItem struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type ApiListReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Name     string `json:"name,optional" form:"name,optional"`
}

type ApiListResp struct {
	Total int64     `json:"total"`
	List  []ApiItem `json:"list"`
}

type ApiUpdateReq struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name,optional"`
	Method      string `json:"method,optional"`
	Path        string `json:"path,optional"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type DepartmentCreateReq struct {
	ParentId uint64 `json:"parentId"`
	Name     string `json:"name"`
	OrderNum int64  `json:"orderNum,optional"`
	Status   int64  `json:"status,optional"`
}

type DepartmentDeleteReq struct {
	Id uint64 `json:"id"`
}

type DepartmentItem struct {
	Id       uint64           `json:"id"`
	ParentId uint64           `json:"parentId"`
	Name     string           `json:"name"`
	OrderNum int64            `json:"orderNum"`
	Status   int64            `json:"status"`
	Children []DepartmentItem `json:"children,optional"`
}

type DepartmentTreeResp struct {
	List []DepartmentItem `json:"list"`
}

type DepartmentUpdateReq struct {
	Id       uint64 `json:"id"`
	ParentId uint64 `json:"parentId"`
	Name     string `json:"name"`
	OrderNum int64  `json:"orderNum,optional"`
	Status   int64  `json:"status,optional"`
}

type FileCreateReq struct {
	Name   string `json:"name"`
	Status int64  `json:"status,optional"`
}

type FileDeleteReq struct {
	Id uint64 `json:"id"`
}

type FileItem struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`
	Status    int64  `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type FileListReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Name     string `json:"name,optional" form:"name,optional"`
}

type FileListResp struct {
	Total int64      `json:"total"`
	List  []FileItem `json:"list"`
}

type FileUpdateReq struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name,optional"`
	Status int64  `json:"status,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LogoutReq struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type MenuCreateReq struct {
	ParentId  uint64 `json:"parentId"`
	Name      string `json:"name"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	MenuType  int64  `json:"type"`
	OrderNum  int64  `json:"orderNum,optional"`
	Visible   int64  `json:"visible,optional"`
	Status    int64  `json:"status,optional"`
}

type MenuDeleteReq struct {
	Id uint64 `json:"id"`
}

type MenuItem struct {
	Id        uint64     `json:"id"`
	ParentId  uint64     `json:"parentId"`
	Name      string     `json:"name"`
	Path      string     `json:"path"`
	Component string     `json:"component"`
	Icon      string     `json:"icon"`
	MenuType  int64      `json:"type"` // 1 目录 2 菜单 3 按钮
	OrderNum  int64      `json:"orderNum"`
	Visible   int64      `json:"visible"`
	Status    int64      `json:"status"`
	Children  []MenuItem `json:"children,optional"`
}

type MenuTreeResp struct {
	List []MenuItem `json:"list"`
}

type MenuUpdateReq struct {
	Id        uint64 `json:"id"`
	ParentId  uint64 `json:"parentId"`
	Name      string `json:"name"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	MenuType  int64  `json:"type"`
	OrderNum  int64  `json:"orderNum,optional"`
	Visible   int64  `json:"visible,optional"`
	Status    int64  `json:"status,optional"`
}

type PermissionApiListReq struct {
	PermissionId uint64 `json:"permissionId,optional" form:"permissionId,optional"`
}

type PermissionApiListResp struct {
	ApiIds []uint64 `json:"apiIds"`
}

type PermissionApiUpdateReq struct {
	PermissionId uint64   `json:"permissionId"`
	ApiIds       []uint64 `json:"apiIds"`
}

type PermissionCreateReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
}

type PermissionDeleteReq struct {
	Id uint64 `json:"id"`
}

type PermissionItem struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type PermissionListReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Name     string `json:"name,optional" form:"name,optional"`
}

type PermissionListResp struct {
	Total int64            `json:"total"`
	List  []PermissionItem `json:"list"`
}

type PermissionMenuListReq struct {
	PermissionId uint64 `json:"permissionId,optional" form:"permissionId,optional"`
}

type PermissionMenuListResp struct {
	MenuIds []uint64 `json:"menuIds"`
}

type PermissionMenuUpdateReq struct {
	PermissionId uint64   `json:"permissionId"`
	MenuIds      []uint64 `json:"menuIds"`
}

type PermissionUpdateReq struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type PingResp struct {
	Message string `json:"message"`
}

type ProfileResp struct {
	Id          uint64   `json:"id"`
	Username    string   `json:"username"`
	Permissions []string `json:"permissions,optional"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RoleCreateReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type RoleDeleteReq struct {
	Id uint64 `json:"id"`
}

type RoleItem struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
}

type RoleListReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Name     string `json:"name,optional" form:"name,optional"`
}

type RoleListResp struct {
	Total int64      `json:"total"`
	List  []RoleItem `json:"list"`
}

type RolePermissionListReq struct {
	RoleId uint64 `json:"roleId,optional" form:"roleId,optional"`
}

type RolePermissionListResp struct {
	PermissionIds []uint64 `json:"permissionIds"`
}

type RolePermissionUpdateReq struct {
	RoleId        uint64   `json:"roleId"`
	PermissionIds []uint64 `json:"permissionIds"`
}

type RoleUpdateReq struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type UserCreateReq struct {
	Username     string `json:"username"`
	Password     string `json:"password"`
	DepartmentId uint64 `json:"departmentId"`
	Status       int64  `json:"status,optional"`
}

type UserDeleteReq struct {
	Id uint64 `json:"id"`
}

type UserItem struct {
	Id           uint64 `json:"id"`
	Username     string `json:"username"`
	DepartmentId uint64 `json:"departmentId"`
	Status       int64  `json:"status"`
	CreatedAt    string `json:"createdAt"`
}

type UserListReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Username string `json:"username,optional" form:"username,optional"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserItem `json:"list"`
}

type UserRoleListReq struct {
	UserId uint64 `json:"userId,optional" form:"userId,optional"`
}

type UserRoleListResp struct {
	RoleIds []uint64 `json:"roleIds"`
}

type UserRoleUpdateReq struct {
	UserId  uint64   `json:"userId"`
	RoleIds []uint64 `json:"roleIds"`
}

type UserUpdateReq struct {
	Id           uint64 `json:"id"`
	Username     string `json:"username,optional"`
	Password     string `json:"password,optional"`
	DepartmentId uint64 `json:"departmentId,optional"`
	Status       int64  `json:"status,optional"`
}
