// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb3 {

  /// <summary>Holder for reflection information generated from error_code.proto</summary>
  public static partial class ErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlcnJvcl9jb2RlLnByb3RvEgNwYjMqggEKCUVycm9yQ29kZRILCgdTdWNj",
            "ZXNzEAASEwoOSW50ZXJuYWxfRXJyb3IQ6AcSEgoNUGFyYW1fSW52YWxpZBDp",
            "BxIUCg9OZXR3b3JrX1RpbWVvdXQQ0Q8SFAoPUGxheWVyX05vdEZvdW5kELkX",
            "EhMKDkl0ZW1fTm90RW5vdWdoEIknQhpaGHNlcnZlci9pbnRlcm5hbC9wcm90",
            "b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb3.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 通用错误码，全局唯一。
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("Success")] Success = 0,
    /// <summary>
    /// 系统内部错误
    /// </summary>
    [pbr::OriginalName("Internal_Error")] InternalError = 1000,
    /// <summary>
    /// 参数不合法
    /// </summary>
    [pbr::OriginalName("Param_Invalid")] ParamInvalid = 1001,
    /// <summary>
    /// 网络超时
    /// </summary>
    [pbr::OriginalName("Network_Timeout")] NetworkTimeout = 2001,
    /// <summary>
    /// 找不到玩家
    /// </summary>
    [pbr::OriginalName("Player_NotFound")] PlayerNotFound = 3001,
    /// <summary>
    /// 道具数量不足
    /// </summary>
    [pbr::OriginalName("Item_NotEnough")] ItemNotEnough = 5001,
  }

  #endregion

}

#endregion Designer generated code
