// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fuben_def.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb3 {

  /// <summary>Holder for reflection information generated from fuben_def.proto</summary>
  public static partial class FubenDefReflection {

    #region Descriptor
    /// <summary>File descriptor for fuben_def.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FubenDefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9mdWJlbl9kZWYucHJvdG8SA3BiMypJCglGdUJlblR5cGUSEAoMRnVCZW5U",
            "eXBlTmlsEAASFgoSRnVCZW5UeXBlUGVybWFuZW50EAESEgoORnVCZW5UeXBl",
            "VGltZWQQAip7CgpGdUJlblN0YXRlEhEKDUZ1QmVuU3RhdGVOaWwQABIUChBG",
            "dUJlblN0YXRlTm9ybWFsEAESFQoRRnVCZW5TdGF0ZUNsb3NpbmcQAhIUChBG",
            "dUJlblN0YXRlQ2xvc2VkEAMSFwoTRnVCZW5TdGF0ZUNvbXBsZXRlZBAEQhpa",
            "GHNlcnZlci9pbnRlcm5hbC9wcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb3.FuBenType), typeof(global::Pb3.FuBenState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FuBenType {
    [pbr::OriginalName("FuBenTypeNil")] Nil = 0,
    /// <summary>
    /// 常驻副本
    /// </summary>
    [pbr::OriginalName("FuBenTypePermanent")] Permanent = 1,
    /// <summary>
    /// 限时副本
    /// </summary>
    [pbr::OriginalName("FuBenTypeTimed")] Timed = 2,
  }

  public enum FuBenState {
    [pbr::OriginalName("FuBenStateNil")] Nil = 0,
    /// <summary>
    /// 正常
    /// </summary>
    [pbr::OriginalName("FuBenStateNormal")] Normal = 1,
    /// <summary>
    /// 关闭中
    /// </summary>
    [pbr::OriginalName("FuBenStateClosing")] Closing = 2,
    /// <summary>
    /// 已关闭
    /// </summary>
    [pbr::OriginalName("FuBenStateClosed")] Closed = 3,
    /// <summary>
    /// 已完成（结算中）
    /// </summary>
    [pbr::OriginalName("FuBenStateCompleted")] Completed = 4,
  }

  #endregion

}

#endregion Designer generated code
