// Code generated by goctl. DO NOT EDIT.
// goctl {{.version}}

package handler

import (
	"net/http"{{if .hasTimeout}}
	"time"{{end}}

	"github.com/zeromicro/go-zero/rest"
	"postapocgame/admin-server/internal/middleware"
	{{.importPackages}}
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{{.routesAdditions}}
}
