//*
// @Author: zjj
// @Date: 2025/11/12
// @Desc: 属性系统定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: attr_def.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 属性系统枚举
type SaAttrSys int32

const (
	SaAttrSys_SaAttrSysNil SaAttrSys = 0
	SaAttrSys_SaLevel      SaAttrSys = 1 // 等级系统
	SaAttrSys_SaEquip      SaAttrSys = 2 // 装备系统
)

// Enum value maps for SaAttrSys.
var (
	SaAttrSys_name = map[int32]string{
		0: "SaAttrSysNil",
		1: "SaLevel",
		2: "SaEquip",
	}
	SaAttrSys_value = map[string]int32{
		"SaAttrSysNil": 0,
		"SaLevel":      1,
		"SaEquip":      2,
	}
)

func (x SaAttrSys) Enum() *SaAttrSys {
	p := new(SaAttrSys)
	*p = x
	return p
}

func (x SaAttrSys) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaAttrSys) Descriptor() protoreflect.EnumDescriptor {
	return file_attr_def_proto_enumTypes[0].Descriptor()
}

func (SaAttrSys) Type() protoreflect.EnumType {
	return &file_attr_def_proto_enumTypes[0]
}

func (x SaAttrSys) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaAttrSys.Descriptor instead.
func (SaAttrSys) EnumDescriptor() ([]byte, []int) {
	return file_attr_def_proto_rawDescGZIP(), []int{0}
}

// 属性同步数据（单个系统的属性数据）
type SyncAttrData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrData map[uint32]*AttrVec `protobuf:"bytes,1,rep,name=attr_data,json=attrData,proto3" json:"attr_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // key: SaAttrSys枚举值, value: 该系统的属性列表
}

func (x *SyncAttrData) Reset() {
	*x = SyncAttrData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attr_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAttrData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAttrData) ProtoMessage() {}

func (x *SyncAttrData) ProtoReflect() protoreflect.Message {
	mi := &file_attr_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAttrData.ProtoReflect.Descriptor instead.
func (*SyncAttrData) Descriptor() ([]byte, []int) {
	return file_attr_def_proto_rawDescGZIP(), []int{0}
}

func (x *SyncAttrData) GetAttrData() map[uint32]*AttrVec {
	if x != nil {
		return x.AttrData
	}
	return nil
}

// 属性列表（用于属性同步）
type AttrVec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attrs []*AttrSt `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty"`
}

func (x *AttrVec) Reset() {
	*x = AttrVec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attr_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrVec) ProtoMessage() {}

func (x *AttrVec) ProtoReflect() protoreflect.Message {
	mi := &file_attr_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrVec.ProtoReflect.Descriptor instead.
func (*AttrVec) Descriptor() ([]byte, []int) {
	return file_attr_def_proto_rawDescGZIP(), []int{1}
}

func (x *AttrVec) GetAttrs() []*AttrSt {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_attr_def_proto protoreflect.FileDescriptor

var file_attr_def_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x70, 0x62, 0x33, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x74, 0x74, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x3c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x41, 0x74, 0x74, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x49, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x72, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x56, 0x65, 0x63,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2c, 0x0a, 0x07, 0x41,
	0x74, 0x74, 0x72, 0x56, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x53, 0x74, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x2a, 0x37, 0x0a, 0x09, 0x53, 0x61, 0x41,
	0x74, 0x74, 0x72, 0x53, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x61, 0x41, 0x74, 0x74, 0x72,
	0x53, 0x79, 0x73, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x61, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x61, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x10, 0x02, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_attr_def_proto_rawDescOnce sync.Once
	file_attr_def_proto_rawDescData = file_attr_def_proto_rawDesc
)

func file_attr_def_proto_rawDescGZIP() []byte {
	file_attr_def_proto_rawDescOnce.Do(func() {
		file_attr_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_attr_def_proto_rawDescData)
	})
	return file_attr_def_proto_rawDescData
}

var file_attr_def_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attr_def_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_attr_def_proto_goTypes = []interface{}{
	(SaAttrSys)(0),       // 0: pb3.SaAttrSys
	(*SyncAttrData)(nil), // 1: pb3.SyncAttrData
	(*AttrVec)(nil),      // 2: pb3.AttrVec
	nil,                  // 3: pb3.SyncAttrData.AttrDataEntry
	(*AttrSt)(nil),       // 4: pb3.AttrSt
}
var file_attr_def_proto_depIdxs = []int32{
	3, // 0: pb3.SyncAttrData.attr_data:type_name -> pb3.SyncAttrData.AttrDataEntry
	4, // 1: pb3.AttrVec.attrs:type_name -> pb3.AttrSt
	2, // 2: pb3.SyncAttrData.AttrDataEntry.value:type_name -> pb3.AttrVec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_attr_def_proto_init() }
func file_attr_def_proto_init() {
	if File_attr_def_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_attr_def_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAttrData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attr_def_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrVec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attr_def_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attr_def_proto_goTypes,
		DependencyIndexes: file_attr_def_proto_depIdxs,
		EnumInfos:         file_attr_def_proto_enumTypes,
		MessageInfos:      file_attr_def_proto_msgTypes,
	}.Build()
	File_attr_def_proto = out.File
	file_attr_def_proto_rawDesc = nil
	file_attr_def_proto_goTypes = nil
	file_attr_def_proto_depIdxs = nil
}
