//*
// @Author: zjj
// @Date: 2025/11/12
// @Desc: C -> S

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: cs.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SProtocol int32

const (
	C2SProtocol_C2SProtocolNil        C2SProtocol = 0
	C2SProtocol_C2SRegister           C2SProtocol = 1  // 账号注册
	C2SProtocol_C2SLogin              C2SProtocol = 2  // 账号登录
	C2SProtocol_C2SVerify             C2SProtocol = 3  // 验证请求
	C2SProtocol_C2SQueryRoles         C2SProtocol = 4  // 查询角色列表
	C2SProtocol_C2SCreateRole         C2SProtocol = 5  // 创建角色
	C2SProtocol_C2SEnterGame          C2SProtocol = 6  // 进入游戏
	C2SProtocol_C2SReconnect          C2SProtocol = 7  // 重连请求
	C2SProtocol_C2SUseSkill           C2SProtocol = 8  // 使用技能
	C2SProtocol_C2SStartMove          C2SProtocol = 9  // 开始移动
	C2SProtocol_C2SUpdateMove         C2SProtocol = 10 // 移动中更新
	C2SProtocol_C2SEndMove            C2SProtocol = 11 // 结束移动
	C2SProtocol_C2SOpenBag            C2SProtocol = 12 // 查询背包
	C2SProtocol_C2SOpenMoney          C2SProtocol = 13 // 查询货币
	C2SProtocol_C2SShopBuy            C2SProtocol = 14 // 商城购买
	C2SProtocol_C2SEquipItem          C2SProtocol = 15 // 穿戴装备
	C2SProtocol_C2SGMCommand          C2SProtocol = 16 // GM命令
	C2SProtocol_C2SUseItem            C2SProtocol = 17 // 使用物品
	C2SProtocol_C2SRecycleItem        C2SProtocol = 18 // 回收物品
	C2SProtocol_C2STalkToNPC          C2SProtocol = 19 // 和NPC对话
	C2SProtocol_C2SLearnSkill         C2SProtocol = 20 // 学习技能
	C2SProtocol_C2SUpgradeSkill       C2SProtocol = 21 // 升级技能
	C2SProtocol_C2SChangeScene        C2SProtocol = 22 // 切换场景
	C2SProtocol_C2SPickupItem         C2SProtocol = 23 // 拾取掉落物
	C2SProtocol_C2SEnterDungeon       C2SProtocol = 24 // 进入副本（限时副本）
	C2SProtocol_C2SClaimOfflineReward C2SProtocol = 25 // 领取离线收益
	C2SProtocol_C2SRevive             C2SProtocol = 26 // 角色复活
	C2SProtocol_C2SGetNearestMonster  C2SProtocol = 27 // 获取最近怪物
	C2SProtocol_C2SChatWorld          C2SProtocol = 28 // 世界聊天
	C2SProtocol_C2SChatPrivate        C2SProtocol = 29 // 私聊
	C2SProtocol_C2SAddFriend          C2SProtocol = 30 // 添加好友
	C2SProtocol_C2SRespondFriendReq   C2SProtocol = 31 // 响应好友申请
	C2SProtocol_C2SQueryFriendList    C2SProtocol = 32 // 查询好友列表
	C2SProtocol_C2SRemoveFriend       C2SProtocol = 33 // 删除好友
	C2SProtocol_C2SQueryRank          C2SProtocol = 34 // 查询排行榜
	C2SProtocol_C2SCreateGuild        C2SProtocol = 35 // 创建公会
	C2SProtocol_C2SJoinGuild          C2SProtocol = 36 // 加入公会
	C2SProtocol_C2SLeaveGuild         C2SProtocol = 37 // 离开公会
	C2SProtocol_C2SQueryGuildInfo     C2SProtocol = 38 // 查询公会信息
	C2SProtocol_C2SAuctionPutOn       C2SProtocol = 39 // 拍卖上架
	C2SProtocol_C2SAuctionBuy         C2SProtocol = 40 // 拍卖购买
	C2SProtocol_C2SAuctionQuery       C2SProtocol = 41 // 拍卖查询
)

// Enum value maps for C2SProtocol.
var (
	C2SProtocol_name = map[int32]string{
		0:  "C2SProtocolNil",
		1:  "C2SRegister",
		2:  "C2SLogin",
		3:  "C2SVerify",
		4:  "C2SQueryRoles",
		5:  "C2SCreateRole",
		6:  "C2SEnterGame",
		7:  "C2SReconnect",
		8:  "C2SUseSkill",
		9:  "C2SStartMove",
		10: "C2SUpdateMove",
		11: "C2SEndMove",
		12: "C2SOpenBag",
		13: "C2SOpenMoney",
		14: "C2SShopBuy",
		15: "C2SEquipItem",
		16: "C2SGMCommand",
		17: "C2SUseItem",
		18: "C2SRecycleItem",
		19: "C2STalkToNPC",
		20: "C2SLearnSkill",
		21: "C2SUpgradeSkill",
		22: "C2SChangeScene",
		23: "C2SPickupItem",
		24: "C2SEnterDungeon",
		25: "C2SClaimOfflineReward",
		26: "C2SRevive",
		27: "C2SGetNearestMonster",
		28: "C2SChatWorld",
		29: "C2SChatPrivate",
		30: "C2SAddFriend",
		31: "C2SRespondFriendReq",
		32: "C2SQueryFriendList",
		33: "C2SRemoveFriend",
		34: "C2SQueryRank",
		35: "C2SCreateGuild",
		36: "C2SJoinGuild",
		37: "C2SLeaveGuild",
		38: "C2SQueryGuildInfo",
		39: "C2SAuctionPutOn",
		40: "C2SAuctionBuy",
		41: "C2SAuctionQuery",
	}
	C2SProtocol_value = map[string]int32{
		"C2SProtocolNil":        0,
		"C2SRegister":           1,
		"C2SLogin":              2,
		"C2SVerify":             3,
		"C2SQueryRoles":         4,
		"C2SCreateRole":         5,
		"C2SEnterGame":          6,
		"C2SReconnect":          7,
		"C2SUseSkill":           8,
		"C2SStartMove":          9,
		"C2SUpdateMove":         10,
		"C2SEndMove":            11,
		"C2SOpenBag":            12,
		"C2SOpenMoney":          13,
		"C2SShopBuy":            14,
		"C2SEquipItem":          15,
		"C2SGMCommand":          16,
		"C2SUseItem":            17,
		"C2SRecycleItem":        18,
		"C2STalkToNPC":          19,
		"C2SLearnSkill":         20,
		"C2SUpgradeSkill":       21,
		"C2SChangeScene":        22,
		"C2SPickupItem":         23,
		"C2SEnterDungeon":       24,
		"C2SClaimOfflineReward": 25,
		"C2SRevive":             26,
		"C2SGetNearestMonster":  27,
		"C2SChatWorld":          28,
		"C2SChatPrivate":        29,
		"C2SAddFriend":          30,
		"C2SRespondFriendReq":   31,
		"C2SQueryFriendList":    32,
		"C2SRemoveFriend":       33,
		"C2SQueryRank":          34,
		"C2SCreateGuild":        35,
		"C2SJoinGuild":          36,
		"C2SLeaveGuild":         37,
		"C2SQueryGuildInfo":     38,
		"C2SAuctionPutOn":       39,
		"C2SAuctionBuy":         40,
		"C2SAuctionQuery":       41,
	}
)

func (x C2SProtocol) Enum() *C2SProtocol {
	p := new(C2SProtocol)
	*p = x
	return p
}

func (x C2SProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2SProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[0].Descriptor()
}

func (C2SProtocol) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[0]
}

func (x C2SProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2SProtocol.Descriptor instead.
func (C2SProtocol) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type C2SRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2SRegisterReq) Reset() {
	*x = C2SRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRegisterReq) ProtoMessage() {}

func (x *C2SRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRegisterReq.ProtoReflect.Descriptor instead.
func (*C2SRegisterReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

func (x *C2SRegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *C2SRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type C2SLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2SLoginReq) Reset() {
	*x = C2SLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLoginReq) ProtoMessage() {}

func (x *C2SLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLoginReq.ProtoReflect.Descriptor instead.
func (*C2SLoginReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *C2SLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *C2SLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type C2SVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SVerifyReq) Reset() {
	*x = C2SVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SVerifyReq) ProtoMessage() {}

func (x *C2SVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SVerifyReq.ProtoReflect.Descriptor instead.
func (*C2SVerifyReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

type C2SQueryRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleList []*PlayerSimpleData `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
}

func (x *C2SQueryRolesReq) Reset() {
	*x = C2SQueryRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SQueryRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQueryRolesReq) ProtoMessage() {}

func (x *C2SQueryRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQueryRolesReq.ProtoReflect.Descriptor instead.
func (*C2SQueryRolesReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

func (x *C2SQueryRolesReq) GetRoleList() []*PlayerSimpleData {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type C2SCreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleData *PlayerSimpleData `protobuf:"bytes,1,opt,name=role_data,json=roleData,proto3" json:"role_data,omitempty"`
}

func (x *C2SCreateRoleReq) Reset() {
	*x = C2SCreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCreateRoleReq) ProtoMessage() {}

func (x *C2SCreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCreateRoleReq.ProtoReflect.Descriptor instead.
func (*C2SCreateRoleReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

func (x *C2SCreateRoleReq) GetRoleData() *PlayerSimpleData {
	if x != nil {
		return x.RoleData
	}
	return nil
}

type C2SEnterGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *C2SEnterGameReq) Reset() {
	*x = C2SEnterGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SEnterGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEnterGameReq) ProtoMessage() {}

func (x *C2SEnterGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEnterGameReq.ProtoReflect.Descriptor instead.
func (*C2SEnterGameReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

func (x *C2SEnterGameReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type C2SReconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReconnectKey string `protobuf:"bytes,1,opt,name=reconnect_key,json=reconnectKey,proto3" json:"reconnect_key,omitempty"`
}

func (x *C2SReconnectReq) Reset() {
	*x = C2SReconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SReconnectReq) ProtoMessage() {}

func (x *C2SReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SReconnectReq.ProtoReflect.Descriptor instead.
func (*C2SReconnectReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

func (x *C2SReconnectReq) GetReconnectKey() string {
	if x != nil {
		return x.ReconnectKey
	}
	return ""
}

type C2SUseSkillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId    uint32   `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetHdl  uint64   `protobuf:"varint,2,opt,name=target_hdl,json=targetHdl,proto3" json:"target_hdl,omitempty"`
	TargetList []uint64 `protobuf:"varint,3,rep,packed,name=target_list,json=targetList,proto3" json:"target_list,omitempty"`
	PosX       uint32   `protobuf:"varint,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY       uint32   `protobuf:"varint,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
}

func (x *C2SUseSkillReq) Reset() {
	*x = C2SUseSkillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUseSkillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUseSkillReq) ProtoMessage() {}

func (x *C2SUseSkillReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUseSkillReq.ProtoReflect.Descriptor instead.
func (*C2SUseSkillReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

func (x *C2SUseSkillReq) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *C2SUseSkillReq) GetTargetHdl() uint64 {
	if x != nil {
		return x.TargetHdl
	}
	return 0
}

func (x *C2SUseSkillReq) GetTargetList() []uint64 {
	if x != nil {
		return x.TargetList
	}
	return nil
}

func (x *C2SUseSkillReq) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *C2SUseSkillReq) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

type C2SStartMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromX uint32 `protobuf:"varint,1,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY uint32 `protobuf:"varint,2,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX   uint32 `protobuf:"varint,3,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY   uint32 `protobuf:"varint,4,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	Speed uint32 `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Seq   uint32 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *C2SStartMoveReq) Reset() {
	*x = C2SStartMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SStartMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SStartMoveReq) ProtoMessage() {}

func (x *C2SStartMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SStartMoveReq.ProtoReflect.Descriptor instead.
func (*C2SStartMoveReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *C2SStartMoveReq) GetFromX() uint32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *C2SStartMoveReq) GetFromY() uint32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *C2SStartMoveReq) GetToX() uint32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *C2SStartMoveReq) GetToY() uint32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

func (x *C2SStartMoveReq) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *C2SStartMoveReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type C2SUpdateMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosX  uint32 `protobuf:"varint,1,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY  uint32 `protobuf:"varint,2,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Speed uint32 `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Seq   uint32 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *C2SUpdateMoveReq) Reset() {
	*x = C2SUpdateMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUpdateMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUpdateMoveReq) ProtoMessage() {}

func (x *C2SUpdateMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUpdateMoveReq.ProtoReflect.Descriptor instead.
func (*C2SUpdateMoveReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

func (x *C2SUpdateMoveReq) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *C2SUpdateMoveReq) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *C2SUpdateMoveReq) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *C2SUpdateMoveReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type C2SEndMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosX uint32 `protobuf:"varint,1,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY uint32 `protobuf:"varint,2,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Seq  uint32 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *C2SEndMoveReq) Reset() {
	*x = C2SEndMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SEndMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEndMoveReq) ProtoMessage() {}

func (x *C2SEndMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEndMoveReq.ProtoReflect.Descriptor instead.
func (*C2SEndMoveReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{10}
}

func (x *C2SEndMoveReq) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *C2SEndMoveReq) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *C2SEndMoveReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type C2SOpenBagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SOpenBagReq) Reset() {
	*x = C2SOpenBagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SOpenBagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOpenBagReq) ProtoMessage() {}

func (x *C2SOpenBagReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOpenBagReq.ProtoReflect.Descriptor instead.
func (*C2SOpenBagReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{11}
}

type C2SOpenMoneyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SOpenMoneyReq) Reset() {
	*x = C2SOpenMoneyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SOpenMoneyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOpenMoneyReq) ProtoMessage() {}

func (x *C2SOpenMoneyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOpenMoneyReq.ProtoReflect.Descriptor instead.
func (*C2SOpenMoneyReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{12}
}

type C2SShopBuyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count  uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *C2SShopBuyReq) Reset() {
	*x = C2SShopBuyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SShopBuyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SShopBuyReq) ProtoMessage() {}

func (x *C2SShopBuyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SShopBuyReq.ProtoReflect.Descriptor instead.
func (*C2SShopBuyReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{13}
}

func (x *C2SShopBuyReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SShopBuyReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type C2SEquipItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Slot   uint32 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *C2SEquipItemReq) Reset() {
	*x = C2SEquipItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SEquipItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipItemReq) ProtoMessage() {}

func (x *C2SEquipItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipItemReq.ProtoReflect.Descriptor instead.
func (*C2SEquipItemReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{14}
}

func (x *C2SEquipItemReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SEquipItemReq) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// GM命令请求
type C2SGMCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GmName string   `protobuf:"bytes,1,opt,name=gm_name,json=gmName,proto3" json:"gm_name,omitempty"` // GM命令名称
	Args   []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                   // GM命令参数数组
}

func (x *C2SGMCommandReq) Reset() {
	*x = C2SGMCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGMCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGMCommandReq) ProtoMessage() {}

func (x *C2SGMCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGMCommandReq.ProtoReflect.Descriptor instead.
func (*C2SGMCommandReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{15}
}

func (x *C2SGMCommandReq) GetGmName() string {
	if x != nil {
		return x.GmName
	}
	return ""
}

func (x *C2SGMCommandReq) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// 使用物品请求
type C2SUseItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count  uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 使用数量（默认1）
}

func (x *C2SUseItemReq) Reset() {
	*x = C2SUseItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUseItemReq) ProtoMessage() {}

func (x *C2SUseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUseItemReq.ProtoReflect.Descriptor instead.
func (*C2SUseItemReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{16}
}

func (x *C2SUseItemReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SUseItemReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 回收物品请求
type C2SRecycleItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count  uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 回收数量（默认1）
}

func (x *C2SRecycleItemReq) Reset() {
	*x = C2SRecycleItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRecycleItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRecycleItemReq) ProtoMessage() {}

func (x *C2SRecycleItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRecycleItemReq.ProtoReflect.Descriptor instead.
func (*C2SRecycleItemReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{17}
}

func (x *C2SRecycleItemReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SRecycleItemReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 和NPC对话请求
type C2STalkToNPCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NpcId uint32 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"` // NPC ID
}

func (x *C2STalkToNPCReq) Reset() {
	*x = C2STalkToNPCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2STalkToNPCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STalkToNPCReq) ProtoMessage() {}

func (x *C2STalkToNPCReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STalkToNPCReq.ProtoReflect.Descriptor instead.
func (*C2STalkToNPCReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{18}
}

func (x *C2STalkToNPCReq) GetNpcId() uint32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

// 学习技能请求
type C2SLearnSkillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId uint32 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"` // 技能ID
}

func (x *C2SLearnSkillReq) Reset() {
	*x = C2SLearnSkillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLearnSkillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLearnSkillReq) ProtoMessage() {}

func (x *C2SLearnSkillReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLearnSkillReq.ProtoReflect.Descriptor instead.
func (*C2SLearnSkillReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{19}
}

func (x *C2SLearnSkillReq) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

// 升级技能请求
type C2SUpgradeSkillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId uint32 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"` // 技能ID
}

func (x *C2SUpgradeSkillReq) Reset() {
	*x = C2SUpgradeSkillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUpgradeSkillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUpgradeSkillReq) ProtoMessage() {}

func (x *C2SUpgradeSkillReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUpgradeSkillReq.ProtoReflect.Descriptor instead.
func (*C2SUpgradeSkillReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{20}
}

func (x *C2SUpgradeSkillReq) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

// 切换场景请求
type C2SChangeSceneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId uint32 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` // 目标场景ID
}

func (x *C2SChangeSceneReq) Reset() {
	*x = C2SChangeSceneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChangeSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChangeSceneReq) ProtoMessage() {}

func (x *C2SChangeSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChangeSceneReq.ProtoReflect.Descriptor instead.
func (*C2SChangeSceneReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{21}
}

func (x *C2SChangeSceneReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// 拾取掉落物请求
type C2SPickupItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemHdl uint64 `protobuf:"varint,1,opt,name=item_hdl,json=itemHdl,proto3" json:"item_hdl,omitempty"` // 掉落物句柄
}

func (x *C2SPickupItemReq) Reset() {
	*x = C2SPickupItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SPickupItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPickupItemReq) ProtoMessage() {}

func (x *C2SPickupItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPickupItemReq.ProtoReflect.Descriptor instead.
func (*C2SPickupItemReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{22}
}

func (x *C2SPickupItemReq) GetItemHdl() uint64 {
	if x != nil {
		return x.ItemHdl
	}
	return 0
}

// 进入副本请求（限时副本）
type C2SClaimOfflineRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SClaimOfflineRewardReq) Reset() {
	*x = C2SClaimOfflineRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SClaimOfflineRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SClaimOfflineRewardReq) ProtoMessage() {}

func (x *C2SClaimOfflineRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SClaimOfflineRewardReq.ProtoReflect.Descriptor instead.
func (*C2SClaimOfflineRewardReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{23}
}

type C2SEnterDungeonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DungeonId  uint32 `protobuf:"varint,1,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"` // 副本ID
	Difficulty uint32 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                // 难度: 1=普通 2=精英 3=地狱
}

func (x *C2SEnterDungeonReq) Reset() {
	*x = C2SEnterDungeonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SEnterDungeonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEnterDungeonReq) ProtoMessage() {}

func (x *C2SEnterDungeonReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEnterDungeonReq.ProtoReflect.Descriptor instead.
func (*C2SEnterDungeonReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{24}
}

func (x *C2SEnterDungeonReq) GetDungeonId() uint32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *C2SEnterDungeonReq) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

// 角色复活请求
type C2SReviveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SReviveReq) Reset() {
	*x = C2SReviveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SReviveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SReviveReq) ProtoMessage() {}

func (x *C2SReviveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SReviveReq.ProtoReflect.Descriptor instead.
func (*C2SReviveReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{25}
}

// 获取最近怪物请求
type C2SGetNearestMonsterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGetNearestMonsterReq) Reset() {
	*x = C2SGetNearestMonsterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGetNearestMonsterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGetNearestMonsterReq) ProtoMessage() {}

func (x *C2SGetNearestMonsterReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGetNearestMonsterReq.ProtoReflect.Descriptor instead.
func (*C2SGetNearestMonsterReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{26}
}

// 添加好友请求
type C2SAddFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId uint64 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标角色ID
}

func (x *C2SAddFriendReq) Reset() {
	*x = C2SAddFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAddFriendReq) ProtoMessage() {}

func (x *C2SAddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAddFriendReq.ProtoReflect.Descriptor instead.
func (*C2SAddFriendReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{27}
}

func (x *C2SAddFriendReq) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 响应好友申请请求
type C2SRespondFriendReqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterId uint64 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // 申请者角色ID
	Accepted    bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`                          // true=同意, false=拒绝
}

func (x *C2SRespondFriendReqReq) Reset() {
	*x = C2SRespondFriendReqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRespondFriendReqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRespondFriendReqReq) ProtoMessage() {}

func (x *C2SRespondFriendReqReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRespondFriendReqReq.ProtoReflect.Descriptor instead.
func (*C2SRespondFriendReqReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{28}
}

func (x *C2SRespondFriendReqReq) GetRequesterId() uint64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *C2SRespondFriendReqReq) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// 查询好友列表请求
type C2SQueryFriendListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SQueryFriendListReq) Reset() {
	*x = C2SQueryFriendListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SQueryFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQueryFriendListReq) ProtoMessage() {}

func (x *C2SQueryFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQueryFriendListReq.ProtoReflect.Descriptor instead.
func (*C2SQueryFriendListReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{29}
}

// 删除好友请求
type C2SRemoveFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友角色ID
}

func (x *C2SRemoveFriendReq) Reset() {
	*x = C2SRemoveFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRemoveFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRemoveFriendReq) ProtoMessage() {}

func (x *C2SRemoveFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRemoveFriendReq.ProtoReflect.Descriptor instead.
func (*C2SRemoveFriendReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{30}
}

func (x *C2SRemoveFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 查询排行榜请求
type C2SQueryRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType RankType `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3,enum=pb3.RankType" json:"rank_type,omitempty"` // 排行榜类型
	TopN     int32    `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`                               // 查询前N名（默认100）
}

func (x *C2SQueryRankReq) Reset() {
	*x = C2SQueryRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SQueryRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQueryRankReq) ProtoMessage() {}

func (x *C2SQueryRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQueryRankReq.ProtoReflect.Descriptor instead.
func (*C2SQueryRankReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{31}
}

func (x *C2SQueryRankReq) GetRankType() RankType {
	if x != nil {
		return x.RankType
	}
	return RankType_RankTypeNil
}

func (x *C2SQueryRankReq) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

// 创建公会请求
type C2SCreateGuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildName string `protobuf:"bytes,1,opt,name=guild_name,json=guildName,proto3" json:"guild_name,omitempty"` // 公会名称
}

func (x *C2SCreateGuildReq) Reset() {
	*x = C2SCreateGuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCreateGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCreateGuildReq) ProtoMessage() {}

func (x *C2SCreateGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCreateGuildReq.ProtoReflect.Descriptor instead.
func (*C2SCreateGuildReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{32}
}

func (x *C2SCreateGuildReq) GetGuildName() string {
	if x != nil {
		return x.GuildName
	}
	return ""
}

// 加入公会请求
type C2SJoinGuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"` // 公会ID
}

func (x *C2SJoinGuildReq) Reset() {
	*x = C2SJoinGuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SJoinGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SJoinGuildReq) ProtoMessage() {}

func (x *C2SJoinGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SJoinGuildReq.ProtoReflect.Descriptor instead.
func (*C2SJoinGuildReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{33}
}

func (x *C2SJoinGuildReq) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

// 离开公会请求
type C2SLeaveGuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SLeaveGuildReq) Reset() {
	*x = C2SLeaveGuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLeaveGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLeaveGuildReq) ProtoMessage() {}

func (x *C2SLeaveGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLeaveGuildReq.ProtoReflect.Descriptor instead.
func (*C2SLeaveGuildReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{34}
}

// 查询公会信息请求
type C2SQueryGuildInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SQueryGuildInfoReq) Reset() {
	*x = C2SQueryGuildInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SQueryGuildInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQueryGuildInfoReq) ProtoMessage() {}

func (x *C2SQueryGuildInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQueryGuildInfoReq.ProtoReflect.Descriptor instead.
func (*C2SQueryGuildInfoReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{35}
}

// 拍卖上架请求
type C2SAuctionPutOnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count    uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 数量
	Price    int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                 // 价格
	Duration int64  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`           // 持续时间（秒）
}

func (x *C2SAuctionPutOnReq) Reset() {
	*x = C2SAuctionPutOnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAuctionPutOnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionPutOnReq) ProtoMessage() {}

func (x *C2SAuctionPutOnReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionPutOnReq.ProtoReflect.Descriptor instead.
func (*C2SAuctionPutOnReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{36}
}

func (x *C2SAuctionPutOnReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SAuctionPutOnReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *C2SAuctionPutOnReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *C2SAuctionPutOnReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 拍卖购买请求
type C2SAuctionBuyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuctionId uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"` // 拍卖ID
}

func (x *C2SAuctionBuyReq) Reset() {
	*x = C2SAuctionBuyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAuctionBuyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionBuyReq) ProtoMessage() {}

func (x *C2SAuctionBuyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionBuyReq.ProtoReflect.Descriptor instead.
func (*C2SAuctionBuyReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{37}
}

func (x *C2SAuctionBuyReq) GetAuctionId() uint64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

// 拍卖查询请求
type C2SAuctionQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // 物品ID（0表示查询所有）
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
}

func (x *C2SAuctionQueryReq) Reset() {
	*x = C2SAuctionQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAuctionQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionQueryReq) ProtoMessage() {}

func (x *C2SAuctionQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionQueryReq.ProtoReflect.Descriptor instead.
func (*C2SAuctionQueryReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{38}
}

func (x *C2SAuctionQueryReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SAuctionQueryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *C2SAuctionQueryReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 世界聊天请求
type C2SChatWorldReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // 聊天内容
}

func (x *C2SChatWorldReq) Reset() {
	*x = C2SChatWorldReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChatWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChatWorldReq) ProtoMessage() {}

func (x *C2SChatWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChatWorldReq.ProtoReflect.Descriptor instead.
func (*C2SChatWorldReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{39}
}

func (x *C2SChatWorldReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 私聊请求
type C2SChatPrivateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId uint64 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标角色ID
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                    // 聊天内容
}

func (x *C2SChatPrivateReq) Reset() {
	*x = C2SChatPrivateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChatPrivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChatPrivateReq) ProtoMessage() {}

func (x *C2SChatPrivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChatPrivateReq.ProtoReflect.Descriptor instead.
func (*C2SChatPrivateReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{40}
}

func (x *C2SChatPrivateReq) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *C2SChatPrivateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x62, 0x33, 0x1a,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0e, 0x43,
	0x32, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x0e, 0x0a, 0x0c,
	0x43, 0x32, 0x53, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x22, 0x46, 0x0a, 0x10,
	0x43, 0x32, 0x53, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x32, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62,
	0x33, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x0f,
	0x43, 0x32, 0x53, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79,
	0x22, 0x95, 0x01, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x68, 0x64, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x48, 0x64, 0x6c, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13,
	0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x43, 0x32, 0x53,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x72,
	0x6f, 0x6d, 0x58, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6d, 0x59, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x6f,
	0x5f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x6f, 0x58, 0x12, 0x11, 0x0a,
	0x04, 0x74, 0x6f, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x6f, 0x59,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x64, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05,
	0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x4b,
	0x0a, 0x0d, 0x43, 0x32, 0x53, 0x45, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x73, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x43,
	0x32, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x61, 0x67, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f,
	0x43, 0x32, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x22,
	0x3e, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x3e, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22,
	0x3e, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x47, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x3e, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x42, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f,
	0x4e, 0x50, 0x43, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x70, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x70, 0x63, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x10, 0x43, 0x32, 0x53, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x12,
	0x43, 0x32, 0x53, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x2e, 0x0a,
	0x11, 0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x10, 0x43, 0x32, 0x53, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x68, 0x64, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x48, 0x64, 0x6c, 0x22, 0x1a, 0x0a, 0x18,
	0x43, 0x32, 0x53, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x22, 0x53, 0x0a, 0x12, 0x43, 0x32, 0x53, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x22, 0x0e, 0x0a,
	0x0c, 0x43, 0x32, 0x53, 0x52, 0x65, 0x76, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22, 0x19, 0x0a,
	0x17, 0x43, 0x32, 0x53, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x2e, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x16, 0x43, 0x32, 0x53, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x52,
	0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x32, 0x53, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x31, 0x0a, 0x12, 0x43, 0x32,
	0x53, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x22, 0x52, 0x0a,
	0x0f, 0x43, 0x32, 0x53, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x2a, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x5f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x6f, 0x70,
	0x4e, 0x22, 0x32, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x32, 0x53, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22,
	0x75, 0x0a, 0x12, 0x43, 0x32, 0x53, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x75, 0x74,
	0x4f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x12, 0x43, 0x32, 0x53,
	0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x32, 0x53,
	0x43, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x43, 0x68, 0x61,
	0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2a, 0xb0, 0x06, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32,
	0x53, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x32, 0x53, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x07, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x10, 0x08, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x10,
	0x09, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f,
	0x76, 0x65, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x45, 0x6e, 0x64, 0x4d, 0x6f,
	0x76, 0x65, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x42,
	0x61, 0x67, 0x10, 0x0c, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x10, 0x0d, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x53, 0x68, 0x6f,
	0x70, 0x42, 0x75, 0x79, 0x10, 0x0e, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x0f, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x47,
	0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10, 0x10, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32,
	0x53, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x11, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32,
	0x53, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x12, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x32, 0x53, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x4e, 0x50, 0x43, 0x10, 0x13,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x10, 0x14, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x10, 0x15, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0x16, 0x12, 0x11, 0x0a, 0x0d,
	0x43, 0x32, 0x53, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x17, 0x12,
	0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x75, 0x6e, 0x67, 0x65,
	0x6f, 0x6e, 0x10, 0x18, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x32, 0x53, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x19, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x52, 0x65, 0x76, 0x69, 0x76, 0x65, 0x10, 0x1a, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x32, 0x53, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x10, 0x1b, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x43,
	0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x10, 0x1c, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32,
	0x53, 0x43, 0x68, 0x61, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x1d, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x32, 0x53, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x1e,
	0x12, 0x17, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x10, 0x1f, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x32, 0x53,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x10,
	0x20, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x10, 0x21, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x10, 0x22, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x23, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x32, 0x53, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x24, 0x12, 0x11,
	0x0a, 0x0d, 0x43, 0x32, 0x53, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10,
	0x25, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x26, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x75, 0x74, 0x4f, 0x6e, 0x10, 0x27, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x32, 0x53, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x79, 0x10, 0x28,
	0x12, 0x13, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x10, 0x29, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_cs_proto_goTypes = []interface{}{
	(C2SProtocol)(0),                 // 0: pb3.C2SProtocol
	(*C2SRegisterReq)(nil),           // 1: pb3.C2SRegisterReq
	(*C2SLoginReq)(nil),              // 2: pb3.C2SLoginReq
	(*C2SVerifyReq)(nil),             // 3: pb3.C2SVerifyReq
	(*C2SQueryRolesReq)(nil),         // 4: pb3.C2SQueryRolesReq
	(*C2SCreateRoleReq)(nil),         // 5: pb3.C2SCreateRoleReq
	(*C2SEnterGameReq)(nil),          // 6: pb3.C2SEnterGameReq
	(*C2SReconnectReq)(nil),          // 7: pb3.C2SReconnectReq
	(*C2SUseSkillReq)(nil),           // 8: pb3.C2SUseSkillReq
	(*C2SStartMoveReq)(nil),          // 9: pb3.C2SStartMoveReq
	(*C2SUpdateMoveReq)(nil),         // 10: pb3.C2SUpdateMoveReq
	(*C2SEndMoveReq)(nil),            // 11: pb3.C2SEndMoveReq
	(*C2SOpenBagReq)(nil),            // 12: pb3.C2SOpenBagReq
	(*C2SOpenMoneyReq)(nil),          // 13: pb3.C2SOpenMoneyReq
	(*C2SShopBuyReq)(nil),            // 14: pb3.C2SShopBuyReq
	(*C2SEquipItemReq)(nil),          // 15: pb3.C2SEquipItemReq
	(*C2SGMCommandReq)(nil),          // 16: pb3.C2SGMCommandReq
	(*C2SUseItemReq)(nil),            // 17: pb3.C2SUseItemReq
	(*C2SRecycleItemReq)(nil),        // 18: pb3.C2SRecycleItemReq
	(*C2STalkToNPCReq)(nil),          // 19: pb3.C2STalkToNPCReq
	(*C2SLearnSkillReq)(nil),         // 20: pb3.C2SLearnSkillReq
	(*C2SUpgradeSkillReq)(nil),       // 21: pb3.C2SUpgradeSkillReq
	(*C2SChangeSceneReq)(nil),        // 22: pb3.C2SChangeSceneReq
	(*C2SPickupItemReq)(nil),         // 23: pb3.C2SPickupItemReq
	(*C2SClaimOfflineRewardReq)(nil), // 24: pb3.C2SClaimOfflineRewardReq
	(*C2SEnterDungeonReq)(nil),       // 25: pb3.C2SEnterDungeonReq
	(*C2SReviveReq)(nil),             // 26: pb3.C2SReviveReq
	(*C2SGetNearestMonsterReq)(nil),  // 27: pb3.C2SGetNearestMonsterReq
	(*C2SAddFriendReq)(nil),          // 28: pb3.C2SAddFriendReq
	(*C2SRespondFriendReqReq)(nil),   // 29: pb3.C2SRespondFriendReqReq
	(*C2SQueryFriendListReq)(nil),    // 30: pb3.C2SQueryFriendListReq
	(*C2SRemoveFriendReq)(nil),       // 31: pb3.C2SRemoveFriendReq
	(*C2SQueryRankReq)(nil),          // 32: pb3.C2SQueryRankReq
	(*C2SCreateGuildReq)(nil),        // 33: pb3.C2SCreateGuildReq
	(*C2SJoinGuildReq)(nil),          // 34: pb3.C2SJoinGuildReq
	(*C2SLeaveGuildReq)(nil),         // 35: pb3.C2SLeaveGuildReq
	(*C2SQueryGuildInfoReq)(nil),     // 36: pb3.C2SQueryGuildInfoReq
	(*C2SAuctionPutOnReq)(nil),       // 37: pb3.C2SAuctionPutOnReq
	(*C2SAuctionBuyReq)(nil),         // 38: pb3.C2SAuctionBuyReq
	(*C2SAuctionQueryReq)(nil),       // 39: pb3.C2SAuctionQueryReq
	(*C2SChatWorldReq)(nil),          // 40: pb3.C2SChatWorldReq
	(*C2SChatPrivateReq)(nil),        // 41: pb3.C2SChatPrivateReq
	(*PlayerSimpleData)(nil),         // 42: pb3.PlayerSimpleData
	(RankType)(0),                    // 43: pb3.RankType
}
var file_cs_proto_depIdxs = []int32{
	42, // 0: pb3.C2SQueryRolesReq.role_list:type_name -> pb3.PlayerSimpleData
	42, // 1: pb3.C2SCreateRoleReq.role_data:type_name -> pb3.PlayerSimpleData
	43, // 2: pb3.C2SQueryRankReq.rank_type:type_name -> pb3.RankType
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	file_base_proto_init()
	file_player_proto_init()
	file_social_def_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SQueryRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SEnterGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SReconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUseSkillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SStartMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUpdateMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SEndMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SOpenBagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SOpenMoneyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SShopBuyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SEquipItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGMCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUseItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRecycleItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2STalkToNPCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLearnSkillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUpgradeSkillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChangeSceneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SPickupItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SClaimOfflineRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SEnterDungeonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SReviveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGetNearestMonsterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAddFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRespondFriendReqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SQueryFriendListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRemoveFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SQueryRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCreateGuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SJoinGuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLeaveGuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SQueryGuildInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAuctionPutOnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAuctionBuyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAuctionQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChatWorldReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChatPrivateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		EnumInfos:         file_cs_proto_enumTypes,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
