//*
// @Author: zjj
// @Date: 2025/11/12
// @Desc: 系统数据定义 proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: system.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemId int32

const (
	SystemId_SystemIdNil      SystemId = 0
	SystemId_SysQuest         SystemId = 1  // 任务系统
	SystemId_SysLevel         SystemId = 2  // 等级系统
	SystemId_SysBag           SystemId = 3  // 背包系统
	SystemId_SysEquip         SystemId = 4  // 装备系统
	SystemId_SysVip           SystemId = 5  // VIP系统
	SystemId_SysMoney         SystemId = 6  // 货币系统
	SystemId_SysAttr          SystemId = 7  // 属性系统
	SystemId_SysOfflineMsg    SystemId = 8  // 离线消息系统
	SystemId_SysMail          SystemId = 9  // 邮件系统
	SystemId_SysShop          SystemId = 10 // 个人商城系统
	SystemId_SysDungeon       SystemId = 11 // 副本系统
	SystemId_SysSkill         SystemId = 12 // 技能系统
	SystemId_SysItemUse       SystemId = 13 // 物品使用系统
	SystemId_SysOfflineReward SystemId = 14 // 离线收益系统
	SystemId_SysAntiCheat     SystemId = 15 // 防作弊系统
	SystemId_SysDailyActivity SystemId = 16 // 日常活跃系统
	SystemId_SysAchievement   SystemId = 17 // 成就系统
	SystemId_SysNewbie        SystemId = 18 // 新手保护系统
	SystemId_SysGM            SystemId = 19 // GM系统
	SystemId_SysFriend        SystemId = 20 // 好友系统
	SystemId_SysGuild         SystemId = 21 // 公会系统
	SystemId_SysAuction       SystemId = 22 // 拍卖行系统
	SystemId_SysChat          SystemId = 23 // 聊天系统
	SystemId_SysRank          SystemId = 24 // 排行榜系统
	SystemId_SysIdMax         SystemId = 25 // 最大系统ID 手动递增
)

// Enum value maps for SystemId.
var (
	SystemId_name = map[int32]string{
		0:  "SystemIdNil",
		1:  "SysQuest",
		2:  "SysLevel",
		3:  "SysBag",
		4:  "SysEquip",
		5:  "SysVip",
		6:  "SysMoney",
		7:  "SysAttr",
		8:  "SysOfflineMsg",
		9:  "SysMail",
		10: "SysShop",
		11: "SysDungeon",
		12: "SysSkill",
		13: "SysItemUse",
		14: "SysOfflineReward",
		15: "SysAntiCheat",
		16: "SysDailyActivity",
		17: "SysAchievement",
		18: "SysNewbie",
		19: "SysGM",
		20: "SysFriend",
		21: "SysGuild",
		22: "SysAuction",
		23: "SysChat",
		24: "SysRank",
		25: "SysIdMax",
	}
	SystemId_value = map[string]int32{
		"SystemIdNil":      0,
		"SysQuest":         1,
		"SysLevel":         2,
		"SysBag":           3,
		"SysEquip":         4,
		"SysVip":           5,
		"SysMoney":         6,
		"SysAttr":          7,
		"SysOfflineMsg":    8,
		"SysMail":          9,
		"SysShop":          10,
		"SysDungeon":       11,
		"SysSkill":         12,
		"SysItemUse":       13,
		"SysOfflineReward": 14,
		"SysAntiCheat":     15,
		"SysDailyActivity": 16,
		"SysAchievement":   17,
		"SysNewbie":        18,
		"SysGM":            19,
		"SysFriend":        20,
		"SysGuild":         21,
		"SysAuction":       22,
		"SysChat":          23,
		"SysRank":          24,
		"SysIdMax":         25,
	}
)

func (x SystemId) Enum() *SystemId {
	p := new(SystemId)
	*p = x
	return p
}

func (x SystemId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemId) Descriptor() protoreflect.EnumDescriptor {
	return file_system_proto_enumTypes[0].Descriptor()
}

func (SystemId) Type() protoreflect.EnumType {
	return &file_system_proto_enumTypes[0]
}

func (x SystemId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemId.Descriptor instead.
func (SystemId) EnumDescriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

// 任务系统
type QuestTypeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quests []*QuestData `protobuf:"bytes,1,rep,name=quests,proto3" json:"quests,omitempty"`
}

func (x *QuestTypeList) Reset() {
	*x = QuestTypeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestTypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestTypeList) ProtoMessage() {}

func (x *QuestTypeList) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestTypeList.ProtoReflect.Descriptor instead.
func (*QuestTypeList) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *QuestTypeList) GetQuests() []*QuestData {
	if x != nil {
		return x.Quests
	}
	return nil
}

type SiQuestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestMap         map[uint32]*QuestTypeList `protobuf:"bytes,1,rep,name=quest_map,json=questMap,proto3" json:"quest_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`                            // key: 任务类型
	LastResetMap     map[uint32]int64          `protobuf:"bytes,2,rep,name=last_reset_map,json=lastResetMap,proto3" json:"last_reset_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`             // key: 任务类型 value: 上次刷新时间
	QuestFinishCount map[uint32]uint32         `protobuf:"bytes,3,rep,name=quest_finish_count,json=questFinishCount,proto3" json:"quest_finish_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // key: 任务ID value: 当天/当周已完成次数（用于 MaxCount 限制）
}

func (x *SiQuestData) Reset() {
	*x = SiQuestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiQuestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiQuestData) ProtoMessage() {}

func (x *SiQuestData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiQuestData.ProtoReflect.Descriptor instead.
func (*SiQuestData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *SiQuestData) GetQuestMap() map[uint32]*QuestTypeList {
	if x != nil {
		return x.QuestMap
	}
	return nil
}

func (x *SiQuestData) GetLastResetMap() map[uint32]int64 {
	if x != nil {
		return x.LastResetMap
	}
	return nil
}

func (x *SiQuestData) GetQuestFinishCount() map[uint32]uint32 {
	if x != nil {
		return x.QuestFinishCount
	}
	return nil
}

// 等级系统
type SiLevelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp   int64  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *SiLevelData) Reset() {
	*x = SiLevelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiLevelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiLevelData) ProtoMessage() {}

func (x *SiLevelData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiLevelData.ProtoReflect.Descriptor instead.
func (*SiLevelData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *SiLevelData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SiLevelData) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 背包系统
type SiBagData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ItemSt `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 通用道具列表
}

func (x *SiBagData) Reset() {
	*x = SiBagData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiBagData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiBagData) ProtoMessage() {}

func (x *SiBagData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiBagData.ProtoReflect.Descriptor instead.
func (*SiBagData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *SiBagData) GetItems() []*ItemSt {
	if x != nil {
		return x.Items
	}
	return nil
}

// VIP 系统
type SiVipData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp   uint32 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *SiVipData) Reset() {
	*x = SiVipData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiVipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiVipData) ProtoMessage() {}

func (x *SiVipData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiVipData.ProtoReflect.Descriptor instead.
func (*SiVipData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *SiVipData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SiVipData) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 货币系统
type SiMoneyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoneyMap map[uint32]int64 `protobuf:"bytes,1,rep,name=moneyMap,proto3" json:"moneyMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // key: 货币类型,
}

func (x *SiMoneyData) Reset() {
	*x = SiMoneyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiMoneyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiMoneyData) ProtoMessage() {}

func (x *SiMoneyData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiMoneyData.ProtoReflect.Descriptor instead.
func (*SiMoneyData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{5}
}

func (x *SiMoneyData) GetMoneyMap() map[uint32]int64 {
	if x != nil {
		return x.MoneyMap
	}
	return nil
}

// 装备系统
type SiEquipData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equips []*EquipSt `protobuf:"bytes,1,rep,name=equips,proto3" json:"equips,omitempty"` // 装备列表
}

func (x *SiEquipData) Reset() {
	*x = SiEquipData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiEquipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiEquipData) ProtoMessage() {}

func (x *SiEquipData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiEquipData.ProtoReflect.Descriptor instead.
func (*SiEquipData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{6}
}

func (x *SiEquipData) GetEquips() []*EquipSt {
	if x != nil {
		return x.Equips
	}
	return nil
}

type EquipSt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId       uint32    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                  // 装备物品ID
	Slot         uint32    `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`                                    // 装备槽位
	Level        uint32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                  // 强化等级
	Exp          uint32    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                                      // 强化经验
	RefineLevel  uint32    `protobuf:"varint,5,opt,name=refine_level,json=refineLevel,proto3" json:"refine_level,omitempty"`   // 精炼等级（0表示未精炼）
	EnchantAttrs []*AttrSt `protobuf:"bytes,6,rep,name=enchant_attrs,json=enchantAttrs,proto3" json:"enchant_attrs,omitempty"` // 附魔属性列表
	SetId        uint32    `protobuf:"varint,7,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`                     // 套装ID（0表示不属于任何套装）
}

func (x *EquipSt) Reset() {
	*x = EquipSt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipSt) ProtoMessage() {}

func (x *EquipSt) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipSt.ProtoReflect.Descriptor instead.
func (*EquipSt) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{7}
}

func (x *EquipSt) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipSt) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *EquipSt) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipSt) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *EquipSt) GetRefineLevel() uint32 {
	if x != nil {
		return x.RefineLevel
	}
	return 0
}

func (x *EquipSt) GetEnchantAttrs() []*AttrSt {
	if x != nil {
		return x.EnchantAttrs
	}
	return nil
}

func (x *EquipSt) GetSetId() uint32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

// 副本系统
type SiDungeonData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*DungeonRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"` // 副本记录列表
}

func (x *SiDungeonData) Reset() {
	*x = SiDungeonData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiDungeonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiDungeonData) ProtoMessage() {}

func (x *SiDungeonData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiDungeonData.ProtoReflect.Descriptor instead.
func (*SiDungeonData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{8}
}

func (x *SiDungeonData) GetRecords() []*DungeonRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type DungeonRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DungeonId     uint32 `protobuf:"varint,1,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`               // 副本ID
	Difficulty    uint32 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                              // 难度: 1=普通 2=精英 3=地狱
	LastEnterTime int64  `protobuf:"varint,3,opt,name=last_enter_time,json=lastEnterTime,proto3" json:"last_enter_time,omitempty"` // 最后进入时间（Unix时间戳）
	EnterCount    uint32 `protobuf:"varint,4,opt,name=enter_count,json=enterCount,proto3" json:"enter_count,omitempty"`            // 今日进入次数
	ResetTime     int64  `protobuf:"varint,5,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`               // 重置时间（Unix时间戳，每日重置）
}

func (x *DungeonRecord) Reset() {
	*x = DungeonRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DungeonRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonRecord) ProtoMessage() {}

func (x *DungeonRecord) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonRecord.ProtoReflect.Descriptor instead.
func (*DungeonRecord) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{9}
}

func (x *DungeonRecord) GetDungeonId() uint32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *DungeonRecord) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *DungeonRecord) GetLastEnterTime() int64 {
	if x != nil {
		return x.LastEnterTime
	}
	return 0
}

func (x *DungeonRecord) GetEnterCount() uint32 {
	if x != nil {
		return x.EnterCount
	}
	return 0
}

func (x *DungeonRecord) GetResetTime() int64 {
	if x != nil {
		return x.ResetTime
	}
	return 0
}

// 邮件系统
type SiMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*MailSt `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails,omitempty"` // 邮件列表
}

func (x *SiMailData) Reset() {
	*x = SiMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiMailData) ProtoMessage() {}

func (x *SiMailData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiMailData.ProtoReflect.Descriptor instead.
func (*SiMailData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{10}
}

func (x *SiMailData) GetMails() []*MailSt {
	if x != nil {
		return x.Mails
	}
	return nil
}

// 技能系统
type SiSkillData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillMap map[uint32]uint32 `protobuf:"bytes,1,rep,name=skill_map,json=skillMap,proto3" json:"skill_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 技能列表（skillId -> level）
}

func (x *SiSkillData) Reset() {
	*x = SiSkillData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiSkillData) ProtoMessage() {}

func (x *SiSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiSkillData.ProtoReflect.Descriptor instead.
func (*SiSkillData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{11}
}

func (x *SiSkillData) GetSkillMap() map[uint32]uint32 {
	if x != nil {
		return x.SkillMap
	}
	return nil
}

// 物品使用系统
type SiItemUseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CooldownMap map[uint32]int64 `protobuf:"bytes,1,rep,name=cooldown_map,json=cooldownMap,proto3" json:"cooldown_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 物品冷却时间记录（itemId -> 冷却结束时间Unix时间戳）
}

func (x *SiItemUseData) Reset() {
	*x = SiItemUseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiItemUseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiItemUseData) ProtoMessage() {}

func (x *SiItemUseData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiItemUseData.ProtoReflect.Descriptor instead.
func (*SiItemUseData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{12}
}

func (x *SiItemUseData) GetCooldownMap() map[uint32]int64 {
	if x != nil {
		return x.CooldownMap
	}
	return nil
}

// 离线收益系统
type SiOfflineRewardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastLogoutTime      int64 `protobuf:"varint,1,opt,name=last_logout_time,json=lastLogoutTime,proto3" json:"last_logout_time,omitempty"`                // 最后登出时间（Unix时间戳）
	TotalOfflineSeconds int64 `protobuf:"varint,2,opt,name=total_offline_seconds,json=totalOfflineSeconds,proto3" json:"total_offline_seconds,omitempty"` // 累计离线时间（秒）
	RewardClaimed       bool  `protobuf:"varint,3,opt,name=reward_claimed,json=rewardClaimed,proto3" json:"reward_claimed,omitempty"`                     // 是否已领取离线收益
	LastClaimTime       int64 `protobuf:"varint,4,opt,name=last_claim_time,json=lastClaimTime,proto3" json:"last_claim_time,omitempty"`                   // 最后领取时间（Unix时间戳）
}

func (x *SiOfflineRewardData) Reset() {
	*x = SiOfflineRewardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiOfflineRewardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiOfflineRewardData) ProtoMessage() {}

func (x *SiOfflineRewardData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiOfflineRewardData.ProtoReflect.Descriptor instead.
func (*SiOfflineRewardData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{13}
}

func (x *SiOfflineRewardData) GetLastLogoutTime() int64 {
	if x != nil {
		return x.LastLogoutTime
	}
	return 0
}

func (x *SiOfflineRewardData) GetTotalOfflineSeconds() int64 {
	if x != nil {
		return x.TotalOfflineSeconds
	}
	return 0
}

func (x *SiOfflineRewardData) GetRewardClaimed() bool {
	if x != nil {
		return x.RewardClaimed
	}
	return false
}

func (x *SiOfflineRewardData) GetLastClaimTime() int64 {
	if x != nil {
		return x.LastClaimTime
	}
	return 0
}

// 防作弊系统
type SiAntiCheatData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationCount    map[string]int32 `protobuf:"bytes,1,rep,name=operation_count,json=operationCount,proto3" json:"operation_count,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`            // 操作计数（操作类型 -> 计数）
	LastOperationTime map[string]int64 `protobuf:"bytes,2,rep,name=last_operation_time,json=lastOperationTime,proto3" json:"last_operation_time,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 最后操作时间（操作类型 -> Unix时间戳）
	SuspiciousCount   int32            `protobuf:"varint,3,opt,name=suspicious_count,json=suspiciousCount,proto3" json:"suspicious_count,omitempty"`                                                                                                 // 可疑行为计数
	LastResetTime     int64            `protobuf:"varint,4,opt,name=last_reset_time,json=lastResetTime,proto3" json:"last_reset_time,omitempty"`                                                                                                     // 最后重置时间（Unix时间戳，用于每日重置）
	IsBanned          bool             `protobuf:"varint,5,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`                                                                                                                      // 是否被封禁
	BanEndTime        int64            `protobuf:"varint,6,opt,name=ban_end_time,json=banEndTime,proto3" json:"ban_end_time,omitempty"`                                                                                                              // 封禁结束时间（Unix时间戳，0表示永久封禁）
}

func (x *SiAntiCheatData) Reset() {
	*x = SiAntiCheatData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiAntiCheatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiAntiCheatData) ProtoMessage() {}

func (x *SiAntiCheatData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiAntiCheatData.ProtoReflect.Descriptor instead.
func (*SiAntiCheatData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{14}
}

func (x *SiAntiCheatData) GetOperationCount() map[string]int32 {
	if x != nil {
		return x.OperationCount
	}
	return nil
}

func (x *SiAntiCheatData) GetLastOperationTime() map[string]int64 {
	if x != nil {
		return x.LastOperationTime
	}
	return nil
}

func (x *SiAntiCheatData) GetSuspiciousCount() int32 {
	if x != nil {
		return x.SuspiciousCount
	}
	return 0
}

func (x *SiAntiCheatData) GetLastResetTime() int64 {
	if x != nil {
		return x.LastResetTime
	}
	return 0
}

func (x *SiAntiCheatData) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *SiAntiCheatData) GetBanEndTime() int64 {
	if x != nil {
		return x.BanEndTime
	}
	return 0
}

// 日常活跃系统
type SiDailyActivityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance       int64                       `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`                                    // 当前活跃点余额
	TodayPoints   uint32                      `protobuf:"varint,2,opt,name=today_points,json=todayPoints,proto3" json:"today_points,omitempty"`         // 今日累计活跃点
	LastResetTime int64                       `protobuf:"varint,3,opt,name=last_reset_time,json=lastResetTime,proto3" json:"last_reset_time,omitempty"` // 最后重置时间（Unix时间戳）
	RewardStates  []*DailyActivityRewardState `protobuf:"bytes,4,rep,name=reward_states,json=rewardStates,proto3" json:"reward_states,omitempty"`       // 奖励领取状态
}

func (x *SiDailyActivityData) Reset() {
	*x = SiDailyActivityData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiDailyActivityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiDailyActivityData) ProtoMessage() {}

func (x *SiDailyActivityData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiDailyActivityData.ProtoReflect.Descriptor instead.
func (*SiDailyActivityData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{15}
}

func (x *SiDailyActivityData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SiDailyActivityData) GetTodayPoints() uint32 {
	if x != nil {
		return x.TodayPoints
	}
	return 0
}

func (x *SiDailyActivityData) GetLastResetTime() int64 {
	if x != nil {
		return x.LastResetTime
	}
	return 0
}

func (x *SiDailyActivityData) GetRewardStates() []*DailyActivityRewardState {
	if x != nil {
		return x.RewardStates
	}
	return nil
}

type DailyActivityRewardState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardId uint32 `protobuf:"varint,1,opt,name=reward_id,json=rewardId,proto3" json:"reward_id,omitempty"` // 奖励ID
	Claimed  bool   `protobuf:"varint,2,opt,name=claimed,proto3" json:"claimed,omitempty"`                   // 是否已领取
}

func (x *DailyActivityRewardState) Reset() {
	*x = DailyActivityRewardState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyActivityRewardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyActivityRewardState) ProtoMessage() {}

func (x *DailyActivityRewardState) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyActivityRewardState.ProtoReflect.Descriptor instead.
func (*DailyActivityRewardState) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{16}
}

func (x *DailyActivityRewardState) GetRewardId() uint32 {
	if x != nil {
		return x.RewardId
	}
	return 0
}

func (x *DailyActivityRewardState) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

// 成就系统
type SiAchievementData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Achievements []*AchievementData `protobuf:"bytes,1,rep,name=achievements,proto3" json:"achievements,omitempty"` // 成就列表
}

func (x *SiAchievementData) Reset() {
	*x = SiAchievementData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiAchievementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiAchievementData) ProtoMessage() {}

func (x *SiAchievementData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiAchievementData.ProtoReflect.Descriptor instead.
func (*SiAchievementData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{17}
}

func (x *SiAchievementData) GetAchievements() []*AchievementData {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type AchievementData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AchievementId uint32   `protobuf:"varint,1,opt,name=achievement_id,json=achievementId,proto3" json:"achievement_id,omitempty"` // 成就ID
	Progress      []uint32 `protobuf:"varint,2,rep,packed,name=progress,proto3" json:"progress,omitempty"`                         // 当前进度
	Completed     bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`                              // 是否已完成
	CompleteTime  int64    `protobuf:"varint,4,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`    // 完成时间（Unix时间戳，0表示未完成）
}

func (x *AchievementData) Reset() {
	*x = AchievementData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AchievementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementData) ProtoMessage() {}

func (x *AchievementData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementData.ProtoReflect.Descriptor instead.
func (*AchievementData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{18}
}

func (x *AchievementData) GetAchievementId() uint32 {
	if x != nil {
		return x.AchievementId
	}
	return 0
}

func (x *AchievementData) GetProgress() []uint32 {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *AchievementData) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *AchievementData) GetCompleteTime() int64 {
	if x != nil {
		return x.CompleteTime
	}
	return 0
}

// 新手保护系统
type SiNewbieData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsNewbie       bool            `protobuf:"varint,1,opt,name=is_newbie,json=isNewbie,proto3" json:"is_newbie,omitempty"`                                                                                                         // 是否处于新手保护期
	NewbieEndTime  int64           `protobuf:"varint,2,opt,name=newbie_end_time,json=newbieEndTime,proto3" json:"newbie_end_time,omitempty"`                                                                                        // 新手保护结束时间（Unix时间戳）
	GuideCompleted bool            `protobuf:"varint,3,opt,name=guide_completed,json=guideCompleted,proto3" json:"guide_completed,omitempty"`                                                                                       // 新手引导是否完成
	GuideProgress  map[uint32]bool `protobuf:"bytes,4,rep,name=guide_progress,json=guideProgress,proto3" json:"guide_progress,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 新手引导进度（引导ID -> 是否完成）
}

func (x *SiNewbieData) Reset() {
	*x = SiNewbieData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiNewbieData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiNewbieData) ProtoMessage() {}

func (x *SiNewbieData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiNewbieData.ProtoReflect.Descriptor instead.
func (*SiNewbieData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{19}
}

func (x *SiNewbieData) GetIsNewbie() bool {
	if x != nil {
		return x.IsNewbie
	}
	return false
}

func (x *SiNewbieData) GetNewbieEndTime() int64 {
	if x != nil {
		return x.NewbieEndTime
	}
	return 0
}

func (x *SiNewbieData) GetGuideCompleted() bool {
	if x != nil {
		return x.GuideCompleted
	}
	return false
}

func (x *SiNewbieData) GetGuideProgress() map[uint32]bool {
	if x != nil {
		return x.GuideProgress
	}
	return nil
}

// 好友系统
type SiFriendData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendList        []uint64 `protobuf:"varint,1,rep,packed,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`                        // 好友ID列表
	FriendRequestList []uint64 `protobuf:"varint,2,rep,packed,name=friend_request_list,json=friendRequestList,proto3" json:"friend_request_list,omitempty"` // 待处理的好友申请列表（别人申请加我为好友）
}

func (x *SiFriendData) Reset() {
	*x = SiFriendData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiFriendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiFriendData) ProtoMessage() {}

func (x *SiFriendData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiFriendData.ProtoReflect.Descriptor instead.
func (*SiFriendData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{20}
}

func (x *SiFriendData) GetFriendList() []uint64 {
	if x != nil {
		return x.FriendList
	}
	return nil
}

func (x *SiFriendData) GetFriendRequestList() []uint64 {
	if x != nil {
		return x.FriendRequestList
	}
	return nil
}

// 公会系统
type SiGuildData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`    // 所属公会ID（0表示未加入公会）
	Position uint32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`                 // 职位（GuildPosition枚举）
	JoinTime int64  `protobuf:"varint,3,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"` // 加入时间（Unix时间戳）
}

func (x *SiGuildData) Reset() {
	*x = SiGuildData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiGuildData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiGuildData) ProtoMessage() {}

func (x *SiGuildData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiGuildData.ProtoReflect.Descriptor instead.
func (*SiGuildData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{21}
}

func (x *SiGuildData) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *SiGuildData) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SiGuildData) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

// 拍卖行系统
type SiAuctionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuctionIdList []uint64 `protobuf:"varint,1,rep,packed,name=auction_id_list,json=auctionIdList,proto3" json:"auction_id_list,omitempty"` // 我上架的拍卖物品ID列表
}

func (x *SiAuctionData) Reset() {
	*x = SiAuctionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiAuctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiAuctionData) ProtoMessage() {}

func (x *SiAuctionData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiAuctionData.ProtoReflect.Descriptor instead.
func (*SiAuctionData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{22}
}

func (x *SiAuctionData) GetAuctionIdList() []uint64 {
	if x != nil {
		return x.AuctionIdList
	}
	return nil
}

var File_system_proto protoreflect.FileDescriptor

var file_system_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x70, 0x62, 0x33, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xc1, 0x03, 0x0a, 0x0b, 0x53, 0x69, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62,
	0x33, 0x2e, 0x53, 0x69, 0x51, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x48, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x62, 0x33, 0x2e, 0x53, 0x69, 0x51, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x12,
	0x54, 0x0a, 0x12, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x62,
	0x33, 0x2e, 0x53, 0x69, 0x51, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x10, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x4f, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3f, 0x0a, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x43, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x0b,
	0x53, 0x69, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x22, 0x2e, 0x0a, 0x09, 0x53, 0x69, 0x42, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x21, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x33, 0x0a, 0x09, 0x53, 0x69, 0x56, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x33,
	0x2e, 0x53, 0x69, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x4d, 0x61, 0x70, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x33, 0x0a, 0x0b, 0x53, 0x69, 0x45, 0x71, 0x75, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x74, 0x52, 0x06,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x07, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x53, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x30, 0x0a, 0x0d, 0x65, 0x6e,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x53, 0x74, 0x52, 0x0c,
	0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x69, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x44, 0x75, 0x6e, 0x67,
	0x65, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x0d, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61,
	0x73, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x72, 0x65, 0x73, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x0a, 0x53,
	0x69, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x05, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x4d,
	0x61, 0x69, 0x6c, 0x53, 0x74, 0x52, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x87, 0x01, 0x0a,
	0x0b, 0x53, 0x69, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x09,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x53, 0x69, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x1a, 0x3b, 0x0a, 0x0d, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x49, 0x74, 0x65,
	0x6d, 0x55, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x46, 0x0a, 0x0c, 0x63, 0x6f, 0x6f, 0x6c,
	0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x70, 0x62, 0x33, 0x2e, 0x53, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x61, 0x70,
	0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xc2, 0x01, 0x0a, 0x13, 0x53, 0x69, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xdc, 0x03, 0x0a, 0x0f, 0x53, 0x69, 0x41, 0x6e, 0x74, 0x69,
	0x43, 0x68, 0x65, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x51, 0x0a, 0x0f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x53, 0x69, 0x41, 0x6e, 0x74, 0x69, 0x43,
	0x68, 0x65, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x5b, 0x0a, 0x13,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x62, 0x33, 0x2e,
	0x53, 0x69, 0x41, 0x6e, 0x74, 0x69, 0x43, 0x68, 0x65, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4c, 0x61, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x73,
	0x70, 0x69, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x75, 0x73, 0x70, 0x69, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x61, 0x6e,
	0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x62, 0x61, 0x6e, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x41, 0x0a, 0x13, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x44,
	0x0a, 0x16, 0x4c, 0x61, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xbe, 0x01, 0x0a, 0x13, 0x53, 0x69, 0x44, 0x61, 0x69, 0x6c, 0x79,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f,
	0x64, 0x61, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x42, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x18, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0x4d, 0x0a, 0x11, 0x53, 0x69, 0x41, 0x63,
	0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a,
	0x0c, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x41, 0x63, 0x68, 0x69, 0x65, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x61, 0x63, 0x68, 0x69, 0x65,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x41, 0x63, 0x68, 0x69,
	0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x61,
	0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x8b, 0x02, 0x0a, 0x0c, 0x53, 0x69, 0x4e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x62, 0x69, 0x65,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x12, 0x4b, 0x0a, 0x0e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x53,
	0x69, 0x4e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x75, 0x69, 0x64,
	0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d,
	0x67, 0x75, 0x69, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x40, 0x0a,
	0x12, 0x47, 0x75, 0x69, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x5f, 0x0a, 0x0c, 0x53, 0x69, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x13, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x11, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x61, 0x0a, 0x0b, 0x53, 0x69, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x69, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0d, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x94, 0x03, 0x0a,
	0x08, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79,
	0x73, 0x51, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x73, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x42, 0x61, 0x67,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x56, 0x69, 0x70, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x79, 0x73, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79,
	0x73, 0x41, 0x74, 0x74, 0x72, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x79, 0x73, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79,
	0x73, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x53, 0x68,
	0x6f, 0x70, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x44, 0x75, 0x6e, 0x67, 0x65,
	0x6f, 0x6e, 0x10, 0x0b, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x73, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65,
	0x10, 0x0d, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x79, 0x73, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x0e, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x41,
	0x6e, 0x74, 0x69, 0x43, 0x68, 0x65, 0x61, 0x74, 0x10, 0x0f, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x79,
	0x73, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x10, 0x10,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x79, 0x73, 0x41, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x10, 0x11, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x79, 0x73, 0x4e, 0x65, 0x77, 0x62, 0x69,
	0x65, 0x10, 0x12, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x79, 0x73, 0x47, 0x4d, 0x10, 0x13, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x79, 0x73, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x14, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x79, 0x73, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x15, 0x12, 0x0e, 0x0a, 0x0a, 0x53,
	0x79, 0x73, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x16, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x79, 0x73, 0x43, 0x68, 0x61, 0x74, 0x10, 0x17, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x52,
	0x61, 0x6e, 0x6b, 0x10, 0x18, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x73, 0x49, 0x64, 0x4d, 0x61,
	0x78, 0x10, 0x19, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData = file_system_proto_rawDesc
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_system_proto_rawDescData)
	})
	return file_system_proto_rawDescData
}

var file_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_system_proto_goTypes = []interface{}{
	(SystemId)(0),                    // 0: pb3.SystemId
	(*QuestTypeList)(nil),            // 1: pb3.QuestTypeList
	(*SiQuestData)(nil),              // 2: pb3.SiQuestData
	(*SiLevelData)(nil),              // 3: pb3.SiLevelData
	(*SiBagData)(nil),                // 4: pb3.SiBagData
	(*SiVipData)(nil),                // 5: pb3.SiVipData
	(*SiMoneyData)(nil),              // 6: pb3.SiMoneyData
	(*SiEquipData)(nil),              // 7: pb3.SiEquipData
	(*EquipSt)(nil),                  // 8: pb3.EquipSt
	(*SiDungeonData)(nil),            // 9: pb3.SiDungeonData
	(*DungeonRecord)(nil),            // 10: pb3.DungeonRecord
	(*SiMailData)(nil),               // 11: pb3.SiMailData
	(*SiSkillData)(nil),              // 12: pb3.SiSkillData
	(*SiItemUseData)(nil),            // 13: pb3.SiItemUseData
	(*SiOfflineRewardData)(nil),      // 14: pb3.SiOfflineRewardData
	(*SiAntiCheatData)(nil),          // 15: pb3.SiAntiCheatData
	(*SiDailyActivityData)(nil),      // 16: pb3.SiDailyActivityData
	(*DailyActivityRewardState)(nil), // 17: pb3.DailyActivityRewardState
	(*SiAchievementData)(nil),        // 18: pb3.SiAchievementData
	(*AchievementData)(nil),          // 19: pb3.AchievementData
	(*SiNewbieData)(nil),             // 20: pb3.SiNewbieData
	(*SiFriendData)(nil),             // 21: pb3.SiFriendData
	(*SiGuildData)(nil),              // 22: pb3.SiGuildData
	(*SiAuctionData)(nil),            // 23: pb3.SiAuctionData
	nil,                              // 24: pb3.SiQuestData.QuestMapEntry
	nil,                              // 25: pb3.SiQuestData.LastResetMapEntry
	nil,                              // 26: pb3.SiQuestData.QuestFinishCountEntry
	nil,                              // 27: pb3.SiMoneyData.MoneyMapEntry
	nil,                              // 28: pb3.SiSkillData.SkillMapEntry
	nil,                              // 29: pb3.SiItemUseData.CooldownMapEntry
	nil,                              // 30: pb3.SiAntiCheatData.OperationCountEntry
	nil,                              // 31: pb3.SiAntiCheatData.LastOperationTimeEntry
	nil,                              // 32: pb3.SiNewbieData.GuideProgressEntry
	(*QuestData)(nil),                // 33: pb3.QuestData
	(*ItemSt)(nil),                   // 34: pb3.ItemSt
	(*AttrSt)(nil),                   // 35: pb3.AttrSt
	(*MailSt)(nil),                   // 36: pb3.MailSt
}
var file_system_proto_depIdxs = []int32{
	33, // 0: pb3.QuestTypeList.quests:type_name -> pb3.QuestData
	24, // 1: pb3.SiQuestData.quest_map:type_name -> pb3.SiQuestData.QuestMapEntry
	25, // 2: pb3.SiQuestData.last_reset_map:type_name -> pb3.SiQuestData.LastResetMapEntry
	26, // 3: pb3.SiQuestData.quest_finish_count:type_name -> pb3.SiQuestData.QuestFinishCountEntry
	34, // 4: pb3.SiBagData.items:type_name -> pb3.ItemSt
	27, // 5: pb3.SiMoneyData.moneyMap:type_name -> pb3.SiMoneyData.MoneyMapEntry
	8,  // 6: pb3.SiEquipData.equips:type_name -> pb3.EquipSt
	35, // 7: pb3.EquipSt.enchant_attrs:type_name -> pb3.AttrSt
	10, // 8: pb3.SiDungeonData.records:type_name -> pb3.DungeonRecord
	36, // 9: pb3.SiMailData.mails:type_name -> pb3.MailSt
	28, // 10: pb3.SiSkillData.skill_map:type_name -> pb3.SiSkillData.SkillMapEntry
	29, // 11: pb3.SiItemUseData.cooldown_map:type_name -> pb3.SiItemUseData.CooldownMapEntry
	30, // 12: pb3.SiAntiCheatData.operation_count:type_name -> pb3.SiAntiCheatData.OperationCountEntry
	31, // 13: pb3.SiAntiCheatData.last_operation_time:type_name -> pb3.SiAntiCheatData.LastOperationTimeEntry
	17, // 14: pb3.SiDailyActivityData.reward_states:type_name -> pb3.DailyActivityRewardState
	19, // 15: pb3.SiAchievementData.achievements:type_name -> pb3.AchievementData
	32, // 16: pb3.SiNewbieData.guide_progress:type_name -> pb3.SiNewbieData.GuideProgressEntry
	1,  // 17: pb3.SiQuestData.QuestMapEntry.value:type_name -> pb3.QuestTypeList
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestTypeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiQuestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiLevelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiBagData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiVipData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiMoneyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiEquipData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipSt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiDungeonData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DungeonRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiSkillData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiItemUseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiOfflineRewardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiAntiCheatData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiDailyActivityData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyActivityRewardState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiAchievementData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AchievementData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiNewbieData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiFriendData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiGuildData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiAuctionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_system_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		EnumInfos:         file_system_proto_enumTypes,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_rawDesc = nil
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
