// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	api "postapocgame/admin-server/internal/handler/api"
	auth "postapocgame/admin-server/internal/handler/auth"
	department "postapocgame/admin-server/internal/handler/department"
	file "postapocgame/admin-server/internal/handler/file"
	menu "postapocgame/admin-server/internal/handler/menu"
	permission "postapocgame/admin-server/internal/handler/permission"
	permission_api "postapocgame/admin-server/internal/handler/permission_api"
	permission_menu "postapocgame/admin-server/internal/handler/permission_menu"
	ping "postapocgame/admin-server/internal/handler/ping"
	role "postapocgame/admin-server/internal/handler/role"
	role_permission "postapocgame/admin-server/internal/handler/role_permission"
	user "postapocgame/admin-server/internal/handler/user"
	user_role "postapocgame/admin-server/internal/handler/user_role"
	"postapocgame/admin-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/apis",
					Handler: api.ApiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/apis",
					Handler: api.ApiCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/apis",
					Handler: api.ApiUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/apis",
					Handler: api.ApiDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: auth.ProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/departments",
					Handler: department.DepartmentCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/departments",
					Handler: department.DepartmentUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/departments",
					Handler: department.DepartmentDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/departments/tree",
					Handler: department.DepartmentTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/files",
					Handler: file.FileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files",
					Handler: file.FileCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/files",
					Handler: file.FileUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/files",
					Handler: file.FileDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menus",
					Handler: menu.MenuCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menus",
					Handler: menu.MenuUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menus",
					Handler: menu.MenuDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menus/my-tree",
					Handler: menu.MenuMyTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menus/tree",
					Handler: menu.MenuTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/permissions",
					Handler: permission.PermissionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permissions",
					Handler: permission.PermissionCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/permissions",
					Handler: permission.PermissionUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/permissions",
					Handler: permission.PermissionDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/permissions/apis",
					Handler: permission_api.PermissionApiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/permissions/apis",
					Handler: permission_api.PermissionApiUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/permissions/menus",
					Handler: permission_menu.PermissionMenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/permissions/menus",
					Handler: permission_menu.PermissionMenuUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: ping.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: role.RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: role.RoleCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/roles",
					Handler: role.RoleUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/roles",
					Handler: role.RoleDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/roles/permissions",
					Handler: role_permission.RolePermissionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/roles/permissions",
					Handler: role_permission.RolePermissionUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.UserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: user.UserCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users",
					Handler: user.UserUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users",
					Handler: user.UserDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/roles",
					Handler: user_role.UserRoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/roles",
					Handler: user_role.UserRoleUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
